### ISSUE TITLE
脚本不能用了

### ISSUE THREAD

**Issue by kong1985** [Lifeng-Liang/EnergyRain#1]
不知道是不是和支付宝更新版本有关系，最近发现能量雨落下不自动点了。看autojs的日志也没有报错。尝试用截图的方式采样绿色能量的图片并用images.read读取替换原来的对比素材，还是不行。
大佬有遇到同样问题嘛？
手机红米note 12 pro+，miui14，支付宝版本号 10.3.60

**Comment by Lifeng-Liang** [comment]
我的两部手机每天使用，没有出现问题，建议重启手机试试。如果还不行，把其中的 debug=false 改为 debug=true 看看 log。
此脚本使用了 opencv 相关函数，AutoxJs 有时候会有 opencv 相关的问题，一般重启能恢复。

**Comment by kong1985** [comment]
好的，感谢回复！
